#!/bin/sh

# quick backup script
# by PenguinSnail and Bithakr
# ------------------------------

#Define variables
#Set destination path and destination device/directory
DEST_PATH=/mnt/quick-back
DEST=$DEST_PATH
#set source path
SRC=/
#Set boolean values for force override, default excludes, and FS formatting
FORCE=0
FORMAT=0
USEDEFAULTS=0
#multiple rsync --excludes
EXCLUDESNUM=0
EXCLUDEDIR=""
#set the rsync options (ALWAYS used)
OPTIONS="-apx --ignore-missing-args --no-i-r --info=progress2 --delete --exclude=$DEST_PATH"
#set the suggested rsync options, used only if -nd,--nodefaults is NOT passed
DEFAULTS="--exclude=/boot/ --exclude=/run/* --exclude=/proc/* --exclude=/tmp/* --exclude=/sys/* --exclude=/dev/* --exclude=/mnt/* --exclude=/media/*"
#set functions dir
functions=/opt/quick-back

#Define functions

usage ()
{
#Display a help dialog for quick-back
printf "%b" "${Bold}${White}Usage: quick-back [OPTION]...\n"
printf "%b" "${Bold}${White}Create an incremental backup to an external drive or directory (using rsync)\n"
printf "%b" "${Bold}${Yellow}Default Backup Directory: ${Green}/mnt/quick-back\n"
printf "%b" "${Bold}${Yellow}Default Source Directory: ${Green}/${Rst}\n"
printf "%b" "${Bold}${Yellow}Default Functions Directory: ${Green}/opt/quick-back${Rst}\n"
printf "%b" "\n"
printf "%b" "	-h, --help | Dispay this help dialog\n"
printf "%b" "	-v, --verbose | Run in verbose mode - display all files being modified without the progress meter\n"
printf "%b" "	-e, --exclude | Exempt another folder from backup (see below for the default excludes)\n"
printf "%b" "	-d, --destination | Use an alternate backup destination (accepts /dev/XXX or a path)\n"
printf "%b" "	-s, --source | Use an alternate source destination\n"
printf "%b" "	-nd, --nodefaults | do not exclude *anything* but the destination mountpoint by default (warning - use carefully or you will overflow your disk!)\n"
printf "%b" "	-c, --color | colorize the output of quick-back\n"
printf "%b" "	--force-ignore | Force backup if destination isn't a mountpoint and ignore destination filesystem type\n"
printf "%b" "\n"
printf "%b" "${Bold}${White}Safety Options\n"
printf "%b" "${Bold}${White}(These reinforce default behavior as of the version in which there are added. No changes will be made to this behavior, except for bugfixes)${Rst}\n"
printf "%b" "\n"
printf "%b" "	-d, --defaults | append the default excludes to the rsync command\n"
printf "%b" "\n"
printf "%b" "${Bold}${Yellow}Default Excludes: ${Green}/boot/, /run/*, /proc/*, /tmp/*, /sys/*, /dev/*, /mnt/*, /media/*${Rst}\n"
printf "%b" "\n"
printf "%b" "${Bold}${White}For support/bugs email: quick-back@freelists.org${Rst}\n"
}


backup ()
{
#backup $SRC to $DEST_PATH
printf "%b" "${Bold}${White}Starting backup ${Rst}(this will take a few minutes)...${Green}${Bold}\n"
CMD="rsync $OPTIONS $SRC/* $DEST_PATH"
#if -nd is NOT passed, concatenate $DEFAULTS with $CMD
if [ "$USEDEFAULTS" = "0" ]; then
   CMD="${CMD} ${DEFAULTS}"
fi
#add any user specified excludes
while [ "$EXCLUDESNUM" -ge 1 ]; do #LIFO queue
	CMD="${CMD} --exclude="
	NEWEXCLUDE=$(echo $EXCLUDEDIR | awk "{ print \$$EXCLUDESNUM }")
    	CMD="${CMD}${NEWEXCLUDE}"
	EXCLUDESNUM=$((EXCLUDESNUM - 1))
done

#run the job
eval "$CMD"
}


backup_boot ()
{
#if /boot exists on the source then
if [ -d "$SRC"/boot ]; then
#run rsync to copy the initramfs and kernel to the backup
printf "%b" "${Bold}${Green}\n"
if ! rsync -apx --no-i-r --info=progress2 --delete "$SRC"/boot/*vmlinuz* "$DEST_PATH"/boot/; then
	printf "%b" "${Bold}${Yellow}failed to backup the kernel${Rst}\n"
	printf "%b" "does it not exist?\n"
fi
printf "%b" "${Bold}${Green}\n"
if ! rsync -apx --no-i-r --info=progress2 --delete "$SRC"/boot/*initramfs* "$DEST_PATH"/boot/; then
	printf "%b" "${Bold}${Yellow}failed to backup the ramfs${Rst}\n"
	printf "%b" "does it not exist?\n"
fi
fi
}


check_force ()
{
#if the forced boolean is true (1) then
if [ "$FORCE" = "1" ]; then
#display a message warning of the fored implications such as fillign storage and non-bootable backups
	printf "%b" "${Bold}${Yellow}You are forcing this program to ignore where it is backing up to.\n"
	printf "%b" "${Bold}${White}If you are backing up to a non-mountpoint destination, you WILL fill up your storage.\n"
	printf "%b" "${Bold}${White}If you are backing up to a mount with a different filesystem, it will not be bootable.${Yellow}\n"
	printf "%b" "Do you wish to continue? [y/N] >${Rst}"
#get confirmation to continue from user
	read -r CONFIRM
#if user input doesnt equal y then exit, else directly skip to the backup function
	if [ "$CONFIRM" != "y" ]; then
		printf "%b" "Exiting program.\n"
		exit 1
	fi
clear
fi
}


check_source () {
#exit if source doesnt exist
if ! df -h "$SRC" > /dev/null; then
	printf "%b" "${Bold}${Red}invalid source${Rst}\n"
	printf "%b" "exiting...\n"
	exit 1
fi
}


backup_path () {
#Determine the path to be used for the backup
#If $DEST is a /dev/xxx device, $DEST_PATH=/mnt/quick-back
case "$DEST" in
	/dev/* )
		DEST_PATH="/mnt/quick-back"
		if [! -d "$DEST_PATH"]; then
			mkdir $DEST_PATH
		fi
	;;
	* )
		#otherwise $DEST_PATH=$DEST
		DEST_PATH="$DEST"
	;;
esac
}


dest_mount () {
#if the force boolean is false then
if [ "$FORCE" = "0" ]; then
	#if the destination path equals destination passed by option
	if [ "$DEST_PATH" = "$DEST" ]; then
		#check if the destination path is not a mountpoint (Found searching /proc/mounts) then
		if ! grep -qs " $DEST_PATH " /proc/mounts; then
			#exit
			printf "%b" "${Bold}${Red}destination path $DEST_PATH is not a mountpoint${Rst}\n"
			printf "%b" "exiting...\n"
			exit 1
		fi
	fi
fi
}


trailing_slash () {
#if source isn't /, remove trailing slash (/) if it exists
if ! [ "$SRC" = "/" ]; then
	last_chr_src=$(echo "$SRC" | tail -c 2)
	if [ "$last_chr_src" = "/" ]; then
		SRC=${SRC%?}
	fi
fi


#remove trailing slash from destination if present
if ! [ "$DEST_PATH" = "/" ]; then
	last_chr_dest=$(echo "$DEST_PATH" | tail -c 2)
	if [ "$last_chr_dest" = "/" ]; then
		DEST_PATH=${DEST_PATH%?}
	fi
elif [ "$DEST_PATH" = "/" ]; then
	printf "%b" "${Bold}${Red}you can't backup to root!${Rst}\n"
	printf "%b" "exiting...\n"
	exit 1
fi
}


src_vars () {
#find top mount of source using df
SRC_MNT=$(df -h "$SRC" | tail -n +2 | awk '{ print $6 }')
#find FS and mount options of source
source_TYPE=$(findmnt -n -o FSTYPE "$SRC_MNT")
source_OPTS=$(findmnt -n -o OPTIONS "$SRC_MNT")
}


mount_dest () {
#if destination is a device (Does it exist in /dev) then
case "$DEST" in
	/dev/* )
		printf "%b" "${Bold}${White}Destination device is ${Green}$DEST\n"
		printf "%b" "${Bold}${White}Mounting ${Green}$DEST ${White}on ${Green}$DEST_PATH${Rst}\n"
		#unmount the device
		umount "$DEST"
		#find out the filesystem of the device
		dest_TYPE="$(blkid /dev/sdb9 | grep -o 'TYPE=[^[:space:]]*' | grep -o '".*"' | sed 's/\"//g')"
		#if the source FS = dest FS then remount with source options
		if [ "$dest_TYPE" = "$source_TYPE" ]; then
			if ! mount "$DEST" -o "$source_OPTS" "$DEST_PATH"; then
				printf "%b" "${Red}${Bold}mount failed${Rst}\n"
				printf "%b" "exiting program...\n"
				exit 1
			fi
			printf "%b" "${Bold}${Cyan}------------------------------${Rst}\n"
		else
		#else remount without options
			if ! mount "$DEST" "$DEST_PATH"; then
				printf "%b" "${Red}${Bold}mount failed${Rst}\n"
				printf "%b" "exiting program...\n"
				exit 1
			fi
			printf "%b" "${Bold}${Cyan}------------------------------${Rst}\n"
		fi
	;;
esac
}


dest_vars () {
#find FS and device of destination
dest_TYPE=$(findmnt -n -o FSTYPE "$DEST_PATH")
dest_DEV=$(findmnt -n -o SOURCE "$DEST_PATH")
}


filesystems_check ()
{
if [ "$FORCE" != "1" ]; then
	if [ "$source_TYPE" != "$dest_TYPE" ]; then
		printf "%b" "${Bold}${Yellow}Your destination filesystem is not the same as your source filesystem\n"
		printf "%b" "${Bold}${White}This may cause issues with permissions and will cause the backup to not be bootable\n"
		printf "%b" "${Bold}${White}Reformat the destination to match the source?\n"
		printf "%b" "${Bold}${Red}WARNING! ${Yellow}This will erase ALL data on the destination! Procede with caution!\n"
		printf "%b" "[y/N] >${Rst}"
		read -r CONFIRM_FS
		if [ "$CONFIRM_FS" != "y" ]; then
			#If user doesnt say yes to format, confirm they wish to continue with the wrong format
			printf "%b" "${Bold}${White}Continue to backup without proper drive format?${Yellow}\n"
			printf "%b" "[y/N] >${Rst}\n"
			read -r FS_CONTINUE
			if [ "$FS_CONTINUE" != "y" ]; then
				#If confirmation doesnt equal y, exit
				exit 1
			fi
			clear
			return
		fi
		clear
		#If the confirmation to format equals y, set format boolean to true (1)
		FORMAT=1
	fi
fi
}

format ()
{
#if the destination is a device, the format boolean is true, and the destination is properly unmounted, format the destination to amtch the source using two different commands. One for btrfs and one for all other FS types
if grep -qs " $DEST_PATH " /proc/mounts; then
	if [ "$FORMAT" = "1" ]; then
		printf "%b" "${Bold}${Yellow}Formating destination device...${Rst}\n"
		printf "%b" "${Bold}${White}\n"
		if umount "$dest_DEV"; then
			if [ "$source_TYPE" = "btrfs" ]; then
				if ! mkfs."$source_TYPE" -f "$dest_DEV"; then
					printf "%b" "${Bold}${Red}failed to format the destination${Rst}\n"
					exit 1
				fi
				printf "%b" "${Bold}${Cyan}------------------------------${Rst}\n"
			else
				if ! mkfs."$source_TYPE" -F "$dest_DEV"; then
					printf "%b" "${Bold}${Red}failed to format the destination${Rst}\n"
					exit 1
				fi
				printf "%b" "${Bold}${Cyan}------------------------------${Rst}\n"
			fi
			#$DEST_PATH="/mnt/quick-back"
			#Run the function to remount the device
			if ! mount "$dest_DEV" -o "$source_OPTS" "$DEST_PATH"; then
				printf "%b" "${Bold}${Red}mount failed${Rst}\n"
				printf "%b" "exiting program...\n"
				exit 1
			fi
		else
			#If unmount fails, exit with error code
			printf "%b" "${Bold}${Red}failed to unmount destination device${Rst}\n"
			printf "%b" "exiting program...\n"
			exit 1
		fi
	fi
fi
}


subvolumes ()
{
if [ "$source_TYPE" = "btrfs" ] && [ "$(findmnt -n -o FSTYPE $DEST_PATH)" = "btrfs" ]; then
btrfs subvolume list -t "$SRC_MNT" | tail -n +3 | awk '{ print $4 }' > /tmp/quick-back-subvolumes
while read -r paths ; do
paths=/$paths
case $paths in
	$SRC* )
		printf "%b" "${Bold}${Green}$paths ${White}is a subvolume in the top level mount${Rst}\n"
		SUBVOL="${paths%$SRC}"
		printf "%b" "${Bold}${Yellow}creating subvolume on $DEST_PATH$SUBVOL${Rst}\n"
		mkdir -p "$DEST_PATH$SUBVOL" > /dev/null 2>&1
		rmdir "$DEST_PATH$SUBVOL" > /dev/null 2>&1
		btrfs subvolume create "$DEST_PATH$SUBVOL" > /dev/null 2>&1
	;;
esac
done < /tmp/quick-back-subvolumes
printf "%b" "${Bold}${Cyan}------------------------------${Rst}\n"
fi
}

#
# EXECUTION STARTS HERE
#

#parse command options
while [ "$1" != "" ]; do
    case $1 in
        -d | --destination )    shift
				DEST=$1
				;;
        -s | --source )         shift
				SRC=$1
				;;
	--force-ignore )        FORCE=1
				;;
	-e | --exclude )	EXCLUDESNUM=$((EXCLUDESNUM+1))
				shift
				EXCLUDEDIR="${EXCLUDEDIR}$1 "
				;;
        -h | --help )           usage
				exit
				;;
	-nd | --nodefaults )	USEDEFAULTS=1
				;;
	-v | --verbose )        OPTIONS="${OPTIONS} -v"
				;;
	-c | --color )		. "$functions/colors.config"
				;;
        * )                     printf "%b" "invalid option \"$1\"\n"
				usage
				exit 1
	esac
    shift
done

#require sudo
if [ "$(id -u)" != 0 ]; then
	printf "%b" "${Bold}${Red}Please run with sudo:${Rst}\n"
	printf "%b" "${Bold}${White}sudo $0 $*${Rst}\n"
	exit 1
fi

#clear screen
clear

#Call functions
check_source
check_force
backup_path
trailing_slash
dest_mount
src_vars
mount_dest
dest_vars
filesystems_check
format
subvolumes
backup
backup_boot
printf "%b" "${Bold}${Cyan}------------------------------${Rst}\n"
printf "%b" "${Bold}${Green}Backup Complete!${Rst}\n"
exit
