#!/bin/bash

# quick backup script
# by PenguinSnail
# ------------------------------

#Define variables
DEST=/mnt/backup
SRC=/
FORCE=0

#Define functions
function usage
{
echo "Usage: quick-back [OPTION]..."
echo "Create an incremental backup to an external drive or directory (using rsync)"
echo "Default Backup Directory: /mnt/backup"
echo "Default Source Directory: /"
echo ""
echo "	-h, --help | Dispay this help dialog"
echo "	-d, --destination | Use an alternate backup destination"
echo "	-s, --source | Use an alternate source destination"
echo "	--force-no-mount | Force backup if destination isn't a mountpoint"
}

function check_dest
{
#check if $DEST is a mountpoint
if ! grep -qs $DEST /proc/mounts; then
	echo "Nothing is mounted on $DEST!"
	exit 1
fi
}

function backup
{
#backup $SRC to $DEST
echo "Starting backup..."
sudo rsync -avpx --delete --exclude=/run/ --exclude=/proc/ --exclude=/tmp/ --exclude=/dev/shm/ --exclude=/sys/ --exclude=/dev/ --exclude=$DEST $SRC/* $DEST
echo "Backup Complete!"
exit
}

function check_force
{
if [ "$FORCE" = "1" ]; then
	echo "You are forcing this program to ignore where it is backing up to."
	echo "If you are backing up to a non-mountpoint destination, you WILL fill up your storage."
	echo -n "Do you wish to continue? [y/N] >"
	read CONFIRM	
	if [ "$CONFIRM" != "y" ]; then
            echo "Exiting program."
            exit 1
        fi
	backup
fi
}

#parse command options
while [ "$1" != "" ]; do
    case $1 in
        -d | --destination )    shift
                                DEST=$1
                                ;;
        -s | --source )         shift
                                SRC=$1
                                ;;
	--force-no-mount )      FORCE=1
                                ;;
        -h | --help )           usage
                                exit
                                ;;
        * )                     usage
                                exit 1
    esac
    shift
done

#require sudo
if [[ $EUID != 0 ]]; then
    echo "Please run with sudo:"
    echo "sudo $0 $*"
    exit 1
fi

#Call functions
check_force
check_dest
backup

